// -------------------------------------------------------------------------- //
// Import the conversion table from old to the new WID codes
// Requires:
// 		$codes_dictionary ($wid_dir/Methodology/Codes_Dictionnary_WID.xlsx)
// Produces:
//		correspondance_table.dta
// TODO: have $codes_dictionary in one Cloud file (with timestamp)
// -------------------------------------------------------------------------- //

assert fileexists("$codes_dictionary")
if fileexists("$work_data/correspondance_table.dta") {
	quietly ashell date -r $work_data/correspondance_table.dta +%s
	local converted = r(o1)
	quietly ashell date -r $codes_dictionary +%s
	local codes_changed = r(o1)
	if `converted' > `codes_changed' {
		di "No conversion needed!"
		exit
	}
	else {
		di "Converting table."
	}
}


// Wealth: macroeconomic variables
import excel using "$codes_dictionary", ///
	sheet("Wealth_Macro_Variables") cellrange(D4:F125) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "m", 1)

tempfile codes
save "`codes'"

// Wealth: distributed variables
import excel using "$codes_dictionary", ///
	sheet("Wealth_Distributed_Variables") cellrange(D4:F22) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "a", 1)

append using "`codes'"
save "`codes'", replace

// Income: distributed variables
import excel using "$codes_dictionary", ///
	sheet("Income_Distributed_Variables") cellrange(D4:F98) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "a", 1)

append using "`codes'"
save "`codes'", replace

// Income: macroeconomic variables
import excel using "$codes_dictionary", ///
	sheet("Income_Macro_Variables") cellrange(D4:F137) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "m", 1)

append using "`codes'"
save "`codes'", replace

// Macro variables: other
import excel using "$codes_dictionary", ///
	sheet("Other_Macro_Variables") cellrange(D4:F17) clear allstring
keep D F
rename D widcode
rename F oldcode

replace widcode = usubinstr(widcode, "*", "m", 1)

append using "`codes'"
save "`codes'", replace

// Other WTID variables
import excel using "$codes_dictionary", ///
	sheet("Other_WTID") cellrange(A4:B123) clear allstring
rename A oldcode
rename B widcode

append using "`codes'"
save "`codes'", replace

duplicates drop
label data "Generated by import-conversion-table.do"
save "$work_data/correspondance-table.dta", replace
