name: Compute analysis

on:
  push:
    branches:
      - main
      - dev-mc
  workflow_dispatch:

jobs:
  compute:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # Workaround - we create a local license file
      - name: Create license
        run: |
            echo "${{ secrets.STATA_LIC_BASE64 }}" | base64 -d > stata.lic 
            ls -l stata.lic
      # we want a lower-case version of the repo name
      - name: Sanitize repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.repository }}'.toLowerCase()
      # Test run Stata file setup.do
      -  name: Compute
         run: "bash -x ./run.sh 'stata-do/setup.do' ./stata.lic"
